# Generated by Django 3.0.3 on 2020-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_pp2m', '0003_city_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('distance', models.IntegerField(default=0.0)),
                ('duration', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'ville'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['num_department'], 'verbose_name': 'département'},
        ),
        migrations.AlterField(
            model_name='city',
            name='is_pref',
            field=models.BooleanField(default=False, verbose_name='préfecture'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_sous_pref',
            field=models.BooleanField(default=False, verbose_name='sous-préfecture'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_department',
            field=models.CharField(max_length=3, verbose_name='département'),
        ),
        migrations.AlterField(
            model_name='city',
            name='postal_code',
            field=models.CharField(max_length=5, verbose_name='code postal'),
        ),
    ]
