# Generated by Django 3.0.3 on 2020-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_pp2m', '0005_auto_20200407_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='pref_name',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='nom'), max_length=200),
        ),
    ]
