# Generated by Django 3.0.3 on 2020-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_pp2m', '0007_city_code_insee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-is_pref', '-is_sous_pref', 'name'], 'verbose_name': 'ville'},
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(default='', max_length=200),
        ),
    ]
