# Generated by Django 3.0.3 on 2020-02-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_department', models.CharField(max_length=3)),
                ('postal_code', models.CharField(max_length=5)),
                ('is_pref', models.BooleanField(default=False)),
                ('is_sous_pref', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('num_department', models.CharField(max_length=3)),
            ],
        ),
    ]
