# Generated by Django 3.0.3 on 2020-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_pp2m', '0002_auto_20200204_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='polygon',
            field=models.TextField(null=True),
        ),
    ]
